window.AFFAIRS_DEMO_DATA = {
  updatedAt: "2026-07-15",
  profiles: {
    undergraduate: {
      id: "undergraduate",
      name: "张同学",
      role: "学生",
      level: "本科生",
      grade: "2024级",
      college: "政府审计学院",
      major: "审计学",
      campus: "浦口校区",
      greeting: "今天有什么校园事务需要处理，尽管告诉我吧！",
      quickQuestions: ["怎么补办学生证？", "图书馆能借多少本书？", "成绩单在哪里打印？", "校园卡丢了怎么办？"],
      tasks: [
        {
          id: "undergrad-scholarship",
          title: "审计长奖学金申请",
          status: "preparing",
          department: "学生工作处 / 所在学院、书院",
          nextStep: "补充成绩及获奖证明",
          deadline: "",
          expectedWindow: "预计 2026 年秋学期，以新通知为准",
          timeBasis: "参考 2025 年第十三届审计长奖学金评选通知，仅用于提前准备材料；2026 年申报时间尚未发布。",
          summary: "根据往年官方评选材料生成的预备任务，不代表 2026 年申报已经启动。",
          materials: [
            { name: "申请表", checked: true },
            { name: "个人事迹材料", checked: true },
            { name: "身份及学籍信息", checked: true },
            { name: "成绩证明", checked: false },
            { name: "获奖证明", checked: false },
          ],
          sourceStatus: "往年规律预估",
          sourceTitle: "第十三届审计长奖学金评选通知",
          sourceUrl: "https://xgc.nau.edu.cn/2025/0402/c3439a142583/page.htm",
        },
        {
          id: "undergrad-transcript",
          title: "成绩单与教务证明打印",
          status: "ready",
          department: "教务处",
          nextStep: "前往文济楼或图书馆一楼自助打印",
          deadline: "",
          deadlineIsDemo: false,
          summary: "文济楼一楼大厅和图书馆一楼大厅均可打印。",
          materials: [{ name: "核对个人信息", checked: true }, { name: "前往自助打印点", checked: false }],
          sourceStatus: "官方已核验",
          sourceTitle: "南京审计大学自助材料打印点",
          sourceUrl: "https://jw.nau.edu.cn/2022/0221/c8184a93542/page.htm",
        },
        {
          id: "undergrad-campus-card",
          title: "校园卡挂失与补办",
          status: "not_started",
          department: "财务处一卡通管理中心",
          nextStep: "立即通过服务网点、自助设备或手机 APP 挂失",
          deadline: "",
          deadlineIsDemo: false,
          summary: "挂失后可使用自助补卡机，或持有效身份证件到服务网点办理。",
          materials: [{ name: "完成挂失", checked: false }, { name: "准备有效身份证件", checked: false }],
          sourceStatus: "官方已核验",
          sourceTitle: "南京审计大学校园“一卡通”管理办法",
          sourceUrl: "https://cwc.nau.edu.cn/2024/0225/c2986a125238/page.htm",
        },
        {
          id: "undergrad-cet",
          title: "2026 年上半年四六级报名",
          status: "completed",
          department: "教务处考试管理科",
          nextStep: "已完成，关注成绩电子报告单",
          deadline: "2026-03-30",
          deadlineIsDemo: false,
          summary: "报名时间为 2026-03-23 12:00 至 2026-03-30 17:00，本卡用于演示完成态。",
          materials: [{ name: "核对学籍与资格信息", checked: true }, { name: "完成报名", checked: true }, { name: "完成缴费", checked: true }],
          sourceStatus: "官方已核验",
          sourceTitle: "2026 年上半年全国大学英语四、六级考试报名通知",
          sourceUrl: "https://jw.nau.edu.cn/2026/0318/c8013a155043/page.htm",
        },
      ],
      priorities: [
        { id: "ug-return", icon: "🏫", tone: "red", title: "秋学期返校准备", description: "提前核对注册、住宿与课表；正式返校时间待学校通知", deadline: "", expectedWindow: "预计 2026 年 9 月前后", timeBasis: "当前未绑定 2026 年正式返校通知，不显示精确日期。", sourceStatus: "待官方通知", sourceUrl: "https://xgc.nau.edu.cn/" },
        { id: "ug-scholarship", icon: "🎓", tone: "orange", title: "奖学金材料准备", description: "参考往年评选材料，提前核对成绩、事迹和获奖证明", deadline: "", expectedWindow: "预计 2026 年秋学期", timeBasis: "参考 2025 年官方评选通知；2026 年申报时间尚未发布。", sourceStatus: "往年规律预估", sourceUrl: "https://xgc.nau.edu.cn/2025/0402/c3439a142583/page.htm" },
        { id: "ug-cet-next", icon: "CET", tone: "blue", title: "下半年四六级报名准备", description: "全国 CET 每年 6 月和 12 月开考；南审下半年报名期尚待教务处通知", deadline: "", expectedWindow: "预计 2026 年 9 月前后开放报名", timeBasis: "依据中国教育考试网公布的年度考试规律及南审 2026 年上半年通知推测，不是正式报名日期。", sourceStatus: "往年规律预估", sourceUrl: "https://cet.neea.edu.cn/", sourceUrls: [{ title: "全国大学英语四、六级考试官网", url: "https://cet.neea.edu.cn/" }, { title: "南审 2026 年上半年报名通知", url: "https://jw.nau.edu.cn/2026/0318/c8013a155043/page.htm" }] },
        { id: "ug-print", icon: "🖨", tone: "green", title: "教务证明自助打印", description: "文济楼或图书馆一楼", deadline: "", deadlineIsDemo: false, sourceStatus: "官方已核验", sourceUrl: "https://jw.nau.edu.cn/2022/0221/c8184a93542/page.htm" },
        { id: "ug-library", icon: "📚", tone: "purple", title: "本科生图书借阅权益", description: "可借 10 册，借期 30 天，可续借 1 次", deadline: "", deadlineIsDemo: false, sourceStatus: "官方已核验", sourceUrl: "https://lib.nau.edu.cn/7017/listm.htm" },
      ],
      notices: [
        { id: "ug-n1", icon: "📘", title: "2026—2027学年第一学期普本学生教材选购通知", summary: "7月12日8:00至7月22日8:00在学生个人信息系统完成教材选购。", timeLabel: "2026-07-10", sourceStatus: "官方已核验", sourceUrl: "https://jw.nau.edu.cn/2026/0710/c8013a160596/page.htm", actionable: false },
        { id: "ug-n2", icon: "📘", title: "2026年获得微专业证书学生名单", summary: "教务处公布2026年获得微专业证书学生名单。", timeLabel: "2026-07-10", sourceStatus: "官方已核验", sourceUrl: "https://jw.nau.edu.cn/2026/0710/c8013a160579/page.htm", actionable: false },
        { id: "ug-n3", icon: "💳", title: "校园卡挂失与补办办法", summary: "丢失后应立即挂失，可通过自助设备或持证到网点补办。", timeLabel: "2024-02-25", sourceStatus: "官方已核验", sourceUrl: "https://cwc.nau.edu.cn/2024/0225/c2986a125238/page.htm", actionable: true, taskId: "undergrad-campus-card" },
        { id: "ug-n4", icon: "📖", title: "利用AI工具与多模态信息辅助学习与科研", summary: "图书馆面向学生发布的信息素养讲座具体通知。", timeLabel: "2026-06-18", sourceStatus: "官方已核验", sourceUrl: "https://lib.nau.edu.cn/2026/0618/c7014a159260/page.htm", actionable: false },
      ],
      recent: ["学生证补办需要哪些材料？", "成绩单可以在哪里打印？", "校园卡挂失后怎么补办？"],
    },
    graduate: {
      id: "graduate",
      name: "江同学",
      role: "学生",
      level: "研究生",
      grade: "2025级",
      college: "国家审计学院",
      major: "审计专业硕士",
      campus: "浦口校区",
      greeting: "我会优先推送培养、学位、奖助和研究生日常事务。",
      quickQuestions: ["研究生奖助学金有哪些？", "研究生图书借阅权益是什么？", "中英文成绩单怎么办？", "最近研究生院有什么通知？"],
      tasks: [
        {
          id: "graduate-scholarship",
          title: "研究生学业奖学金准备",
          status: "preparing",
          department: "研究生院 / 培养学院",
          nextStep: "补充科研成果与社会服务材料",
          deadline: "",
          expectedWindow: "预计 2026 年秋学期，以培养单位通知为准",
          timeBasis: "现有来源介绍奖助体系，但未发布 2026 年本项申报截止日。",
          summary: "根据公开奖助体系生成的材料准备任务，当前年度申报时间待通知。",
          materials: [{ name: "成绩单", checked: true }, { name: "科研成果清单", checked: true }, { name: "社会服务材料", checked: false }, { name: "申请表", checked: false }],
          sourceStatus: "待官方通知",
          sourceTitle: "南京审计大学 2026 年硕士研究生招生简章（奖助体系）",
          sourceUrl: "https://gs.nau.edu.cn/2025/0929/c4394a148065/page.htm",
        },
        {
          id: "graduate-research-plan",
          title: "学位论文开题准备",
          status: "preparing",
          department: "培养学院 / 导师组",
          nextStep: "与导师确认选题及研究计划",
          deadline: "",
          expectedWindow: "建议秋学期提前准备，具体时间待通知",
          timeBasis: "当前未找到适用于该模拟档案的 2026 年开题正式通知，因此不设置日期和倒计时。",
          summary: "这是主动准备提醒，不代表研究生院或培养学院已经发布开题安排。",
          materials: [{ name: "选题方向", checked: true }, { name: "文献综述", checked: false }, { name: "研究计划", checked: false }, { name: "导师意见", checked: false }],
          sourceStatus: "待官方通知",
          sourceTitle: "研究生院学位工作栏目",
          sourceUrl: "https://gs.nau.edu.cn/4416/list.htm",
        },
        {
          id: "graduate-transcript",
          title: "中英文成绩单与学籍证明",
          status: "ready",
          department: "研究生院",
          nextStep: "先核对用途，再前往办理或咨询培养科",
          deadline: "",
          deadlineIsDemo: false,
          summary: "公开网页未完整披露研究生证明全流程，页面保留待确认提示。",
          materials: [{ name: "确认证明用途", checked: true }, { name: "咨询培养科", checked: false }],
          sourceStatus: "待学校确认",
          sourceTitle: "南京审计大学研究生院",
          sourceUrl: "https://gs.nau.edu.cn/",
        },
        {
          id: "graduate-campus-card",
          title: "校园卡挂失与补办",
          status: "not_started",
          department: "财务处一卡通管理中心",
          nextStep: "立即挂失，再持证或使用自助补卡机",
          deadline: "",
          deadlineIsDemo: false,
          summary: "校园卡管理办法同时适用于本科生和研究生。",
          materials: [{ name: "完成挂失", checked: false }, { name: "准备有效身份证件", checked: false }],
          sourceStatus: "官方已核验",
          sourceTitle: "南京审计大学校园“一卡通”管理办法",
          sourceUrl: "https://cwc.nau.edu.cn/2024/0225/c2986a125238/page.htm",
        },
      ],
      priorities: [
        { id: "pg-plan", icon: "🗓", tone: "red", title: "秋学期培养计划确认", description: "提前核对课程、培养环节与导师安排", deadline: "", expectedWindow: "预计 2026 年秋学期开学前后", timeBasis: "尚未绑定 2026 年培养计划确认的正式通知。", sourceStatus: "待官方通知", sourceUrl: "https://gs.nau.edu.cn/4409/list.htm" },
        { id: "pg-scholarship", icon: "🎓", tone: "orange", title: "研究生奖学金材料", description: "公开奖助体系已核验，具体申报时间待培养单位通知", deadline: "", expectedWindow: "预计 2026 年秋学期", timeBasis: "奖助项目来源已核验，但 2026 年申报截止日尚未发布。", sourceStatus: "待官方通知", sourceUrl: "https://gs.nau.edu.cn/2025/0929/c4394a148065/page.htm" },
        { id: "pg-cet", icon: "CET", tone: "blue", title: "下半年四六级报名准备", description: "全国 CET 每年 6 月和 12 月开考；学校报名时间仍需等待南审教务处通知", deadline: "", expectedWindow: "预计 2026 年 9 月前后开放报名", timeBasis: "依据中国教育考试网年度规律及南审上半年通知推测，不是正式报名日期。", sourceStatus: "往年规律预估", sourceUrl: "https://cet.neea.edu.cn/", sourceUrls: [{ title: "全国大学英语四、六级考试官网", url: "https://cet.neea.edu.cn/" }, { title: "南审 2026 年上半年报名通知", url: "https://jw.nau.edu.cn/2026/0318/c8013a155043/page.htm" }] },
        { id: "pg-thesis", icon: "📝", tone: "green", title: "论文开题准备", description: "提前完成选题、文献综述和研究计划；本年度具体时间待通知", deadline: "", expectedWindow: "建议 2026 年秋学期提前准备", timeBasis: "当前未找到适用于该模拟档案的 2026 年正式开题通知。", sourceStatus: "待官方通知", sourceUrl: "https://gs.nau.edu.cn/4416/list.htm" },
        { id: "pg-library", icon: "📚", tone: "purple", title: "研究生图书借阅权益", description: "可借 20 册，借期 60 天，可续借 1 次", deadline: "", deadlineIsDemo: false, sourceStatus: "官方已核验", sourceUrl: "https://lib.nau.edu.cn/7017/listm.htm" },
      ],
      notices: [
        { id: "pg-n1", icon: "🎓", title: "2026年暑期研究生院值班安排", summary: "研究生院发布暑期值班安排，便于在校研究生按时间咨询办理。", timeLabel: "2026-07-13", sourceStatus: "官方已核验", sourceUrl: "https://gs.nau.edu.cn/2026/0713/c4414a160636/page.htm", actionable: false },
        { id: "pg-n2", icon: "🎓", title: "研究生奖助体系", summary: "2026 年招生简章列出国家奖学金、审计长奖学金、国家助学金等项目。", timeLabel: "2025-09-29", sourceStatus: "官方已核验", sourceUrl: "https://gs.nau.edu.cn/2025/0929/c4394a148065/page.htm", actionable: true, taskId: "graduate-scholarship" },
        { id: "pg-n3", icon: "📚", title: "利用AI工具与多模态信息辅助学习与科研", summary: "图书馆面向学习与科研场景发布的线上讲座具体通知。", timeLabel: "2026-06-18", sourceStatus: "官方已核验", sourceUrl: "https://lib.nau.edu.cn/2026/0618/c7014a159260/page.htm", actionable: false },
        { id: "pg-n4", icon: "💳", title: "校园一卡通管理办法", summary: "学生卡丢失应立即挂失，可使用自助补卡机或持证到网点办理。", timeLabel: "2024-02-25", sourceStatus: "官方已核验", sourceUrl: "https://cwc.nau.edu.cn/2024/0225/c2986a125238/page.htm", actionable: true, taskId: "graduate-campus-card" },
      ],
      recent: ["研究生奖助学金包含哪些项目？", "研究生图书可以借多少册？", "最近研究生院有哪些通知？"],
    },
  },
  sharedServices: [
    { id: "teaching-system", icon: "📘", title: "教学信息系统", undergradDesc: "课表、选课、成绩和学籍服务", graduateDesc: "公共教务与考试信息查询", sourceStatus: "官方已核验", sourceUrl: "https://jw.nau.edu.cn/" },
    { id: "graduate-school", icon: "🎓", title: "研究生院", undergradDesc: "研究生招生与教育信息", graduateDesc: "培养、学位、奖助与管理通知", sourceStatus: "官方已核验", sourceUrl: "https://gs.nau.edu.cn/" },
    { id: "library", icon: "📚", title: "图书馆", undergradDesc: "借阅 10 册 / 30 天", graduateDesc: "借阅 20 册 / 60 天", sourceStatus: "官方已核验", sourceUrl: "https://lib.nau.edu.cn/" },
    { id: "campus-map", icon: "📍", title: "校园导航", undergradDesc: "地点查询与校内导航", graduateDesc: "教学楼、研究生院与服务地点", sourceStatus: "官方已核验", sourceUrl: "https://map.nau.edu.cn/" },
    { id: "campus-card", icon: "💳", title: "校园卡服务", undergradDesc: "挂失、补办、充值与异常处理", graduateDesc: "挂失、补办、充值与异常处理", sourceStatus: "官方已核验", sourceUrl: "https://cwc.nau.edu.cn/2024/0225/c2986a125238/page.htm" },
    { id: "printing", icon: "🖨", title: "证明打印", undergradDesc: "成绩单及各类教务证明", graduateDesc: "成绩与学籍证明指引", sourceStatus: "本科流程已核验", sourceUrl: "https://jw.nau.edu.cn/2022/0221/c8184a93542/page.htm" },
    { id: "dormitory", icon: "🔧", title: "宿舍服务", undergradDesc: "入住、调宿、退宿与报修", graduateDesc: "宿舍申请、调整与报修", sourceStatus: "待学校确认", sourceUrl: "https://zwwyh.nau.edu.cn/gygll/" },
    { id: "more", icon: "▦", title: "更多服务", undergradDesc: "信息门户与校园公开服务", graduateDesc: "信息门户与研究生公开服务", sourceStatus: "官方已核验", sourceUrl: "https://www.nau.edu.cn/" },
  ],
};
